### PR TITLE
Fixes Uncaught TypeError: proj4 is not a function

### PR DESCRIPTION
**Pull request by rabbl**
Imports proj4.default to prevent Error: Uncaught TypeError: proj4 is not a function

### CODE REVIEW

**Comment by perliedman** [comment]
@rabbl hi, would you be able to provide some context here, I have never seen that error.

Let me guess that you're seeing this in combination with webpack?

**Comment by perliedman** [comment]
Also, as you can see, this PR currently breaks the build, most likely since `.default` doesn't exist in a normal Node environment.

**Comment by rabbl** [comment]
Hi @perliedman, sorry for bothering you.
Yes, it is a combination with webpack.
Do you have an idea how to fix this in QP without the proposed changes?

**Comment by perliedman** [comment]
@rabbl thinking about this, I think this is more or less exactly the same issue as https://github.com/kartena/Proj4Leaflet/pull/147#issuecomment-303708910 (also a thorough explanation of the problem). I think it might be that a modified version of your PR is the only thing we can do.

That means: after the `require('proj4')`, check if it has `.default`, and use it in that case, otherwise go on as before.

I'd be ok to merge this if you make changes along those lines.

**Comment by rabbl** [comment]
Tests are passing. 
For the webpack-usecase it's also working well.

**Comment by perliedman** [comment]
Nice, thanks!

**Comment by perliedman** [comment]
I published version 1.2.1 with this change just now.

**Pull request merged**
